# Generated by Django 3.0.6 on 2020-05-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0002_auto_20200516_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=11),
        ),
    ]
