# Generated by Django 3.0.6 on 2020-05-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0004_auto_20200517_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
