# Generated by Django 3.0.6 on 2020-05-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0007_auto_20200521_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
