# Generated by Django 3.0.6 on 2020-06-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0008_auto_20200521_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='datahora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
